datasets:
  vqa_rad:
    data_type: images # [images|videos|features]

    build_info:
      annotations:
        train:
          url:
              - https://huggingface.co/datasets/BoKelvin/SLAKE/blob/main/train.json
          storage:
              - /data3/gebinhui/MedVQA/data_RAD/trainset.json
        test:
          url:
             - https://huggingface.co/datasets/BoKelvin/SLAKE/blob/main/validation.json
          storage:
              - /data3/gebinhui/MedVQA/data_RAD/testset.json
      images:
          storage: /data3/gebinhui/MedVQA/data_RAD/images
