datasets:
  slake:
    data_type: images # [images|videos|features]

    build_info:
      annotations:
        train:
          url:
              - https://huggingface.co/datasets/BoKelvin/SLAKE/blob/main/train.json
          storage:
              - /data3/tongzixuan/dataset/Slake/Slakenew/train.json
        val:
          url:
             - https://huggingface.co/datasets/BoKelvin/SLAKE/blob/main/validation.json
          storage:
              - /data3/tongzixuan/dataset/Slake/Slakenew/validate.json
        test:
          url:
              - https://huggingface.co/datasets/BoKelvin/SLAKE/blob/main/test.json
          storage:
              - /data3/tongzixuan/dataset/Slake/Slakenew/test.json
      images:
          storage: /data3/tongzixuan/dataset/Slake/Slakenew
