datasets:
  pmc_caption:
    data_type: images # [images|videos|features]
    build_info:
      annotations:
        train:
          url: https://storage.googleapis.com/sfr-vision-language-research/datasets/coco_karpathy_train.json
          md5: aa31ac474cf6250ebb81d18348a07ed8
          storage: 
      images:
        storage:


