model:
  arch: favp
  model_type: pretrain_vicuna0
  end_sym: "###"
  prompt_template: '###Human: {} ###Assistant: '
  chat_template: False
  freeze_vit: True
  freeze_qformer: True
  q_former_model: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/blip2_pretrained_flant5xxl.pth"
  vit_model: "eva_clip_g"
  has_qformer: True

datasets:
  roco_caption:
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 20
  num_workers: 4
  warmup_steps: 5000

  seed: 42
  output_dir: ""

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: False
  job_name: favp_pretrain